### ISSUE TITLE
Can the RenderPlayer API Enhancer be ported?

### ISSUE THREAD

**Issue by UnixRonin** [Tommsy64/SmartMoving#3]
Divisor used to have a RenderPlayer API Enhancer back in 1.7.10 that identified **MOST** things that used player models (Thaumcraft's Thaumium Fortress armor, for example) and redirected their player-model API calls to RenderPlayer instead, which fixed **MOST** of the compatibility issues.  (But not all; it didn't work with Gender Mod, for a counter-example, and had bizarre whirling-dervish effects on Bibliocraft armor stands.)

Is there any chance of porting that add-on as well?

**Comment by Tommsy64** [comment]
Here you go: [RenderPlayer API Enhancer](https://github.com/Tommsy64/RenderPlayerAPIEnhancer/releases)

At the moment, PlayerAPI, RenderPlayerAPI, and RenderPlayerAPIEnhancer are just repackages without modifications of Divisor's releases from Minecraft Forums.

**Comment by UnixRonin** [comment]
Excellent!!!  Thanks for the fast response  :)
