### ISSUE TITLE
how do we want to handle official communication channels for the update of the mod?

### ISSUE THREAD

**Issue by Too-DAMN-Much** [Tommsy64/SmartMoving#5]
should we have @Tommsy64 create a new minecraft thread or contact moderators to get it updated and transferred over and close the old one or how do you prefer to handle this?

doesn't really matter much to me to be honest, but it's always a bit problematic to leave outdated sources of information around and still appearing to be official.

**Comment by Tommsy64** [comment]
Originally, I created this Smart Moving port just for my own server. At the moment, it will remain an unofficial port until I am able to gain more experience to be able to fully support it.

Also, I haven't contacted Divisor about continuing his mod nor am I sure whether this port should keep the same name ("Smart Moving") as his mod if I do continue to develop it.

**Comment by UnixRonin** [comment]
Then maybe the first step should be to see whether Divisor will give you his blessing.

**Comment by Tommsy64** [comment]
See #12
